spring:
  security:
    oauth2:
      client:
        registration:
          # ?? ??? ??
          google:
            client-id: 729403424984-1p6a6rgb698m2nkg3o6644s3p98hjlo8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile