spring:
  application:
    name: volare
  datasource:
    url: ENC(0B0OtFL/R3Tvff7tCK3zZwSIv78RKrQ5Ops/Nls7y54ldLM/G9Jo+EvzVutrwH3bg8UmCY9IBQ0=)
    username: ENC(pyFe3UZ+UR3DfaU3iFSB8Q==)
    password: ENC(cm3ViRUORYrrZBVk3P/iPqiXOPR6wZtJ)
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          # 구글 로그인 추가
          google:
            client-id: ENC(jVepAyjB8MCtl43ibC/As86j14qCd5rhOaIAuqcDyAi1G1xB7dMhmsaIlYy0xXAwM09qAyiYazSvcO4b1nvR2qZe+KvOg56rVcT0G0A/O5ocKrf2A3eHxQ==)
            client-secret: ENC(fzbhBfBhiXiBuQoychRWFD/29FGrOsL0ZMOcUZ+B3G8opTszGgtojsO+McCY+G4N)
            scope:
              - email
              - profile
          # 네이버 로그인 추가
          naver:
            client-id: ENC(R5WVcUibNcwR8oXFK8tPV7gaV2gsRj5N2ljyxKG3ExI=)
            client-secret: ENC(Nt40ucNchfY/CautqeRQpiWXC6gXhKPB)
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile_image
            client-name: Naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
