spring:
  application:
    name: volare
  datasource:
    url: ENC(0B0OtFL/R3Tvff7tCK3zZwSIv78RKrQ5Ops/Nls7y54ldLM/G9Jo+EvzVutrwH3bg8UmCY9IBQ0=)
    username: ENC(pyFe3UZ+UR3DfaU3iFSB8Q==)
    password: ENC(cm3ViRUORYrrZBVk3P/iPqiXOPR6wZtJ)
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: volare
