spring:
  application:
    name: volare
  datasource:
    url: ENC(jwY6BGUij+iUoWHLrW28+F0qnFzMGSP0+ijG+beAa5RbnxhuaUVAWHJm5b18sFPDmrzoD11qpwc=)
    username: ENC(pyFe3UZ+UR3DfaU3iFSB8Q==)
    password: ENC(cm3ViRUORYrrZBVk3P/iPqiXOPR6wZtJ)
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create
  profiles:
    include: application-private

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
